name: Release Build

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2

    - name: Build Release
      run: swift build -c release

    - name: Package Release
      run: |
        mkdir -p dist
        cp .build/release/mdclip dist/mdclip

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: mdclip-macos
        path: dist/mdclip
